<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<ApplicationIcon>Assets\Icons\InfoID.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfoID.Application\InfoID.Application.csproj" />
    <ProjectReference Include="..\InfoID.Domain\InfoID.Domain.csproj" />
    <ProjectReference Include="..\InfoID.Infrastructure\InfoID.Infrastructure.csproj" />
    <ProjectReference Include="..\InfoID.Shared\InfoID.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <AvaloniaResource Include="Assets\Images\InfoID.png" />
	  <AvaloniaResource Include="Assets\Images\InfoIDLogo.png" />
	  <AvaloniaResource Include="Assets\Icons\InfoID.ico" />
  </ItemGroup>
</Project>
